import uuid


class APIClient:
    """Thin wrapper around backend calls. Instantiate once in app.py and
    pass it into each tab's render() function. Every method currently
    returns placeholder data — the backend teammate swaps the insides
    for real HTTP calls / Claude API calls later, without changing the
    method names or what they return.
    """

    def upload_syllabus(self, file_bytes: bytes, filename: str) -> dict:
        """Real version: multipart POST of the PDF, returns a job/file ID
        to poll via get_scan_status().
        """
        return {"job_id": f"job-{uuid.uuid4().hex[:8]}", "filename": filename}

    def get_scan_status(self, job_id: str) -> dict:
        """Real version: returns queued/processing/complete/failed, plus
        the structured course JSON once complete.
        """
        return {
            "status": "complete",
            "course": {
                "id": f"scan-{uuid.uuid4().hex[:8]}",
                "name": "New Scanned Course",
                "code": "TBD 000",
                "source": "scanned",
                "requirements": [],
            },
        }

    def submit_manual_course(self, course_data: dict) -> dict:
        """Real version: saves a hand-entered course with source='manual'."""
        course = dict(course_data)
        course.setdefault("id", f"manual-{uuid.uuid4().hex[:8]}")
        course["source"] = "manual"
        return course

    def get_courses(self) -> list:
        """Real version: GET all courses. Placeholder returns nothing —
        the app currently keeps courses in st.session_state instead.
        """
        return []

    def update_accommodation(self, course_id: str, excerpt, dismissed: bool = False) -> dict:
        """Real version: PATCH to confirm/edit/dismiss a detected excerpt."""
        return {
            "course_id": course_id,
            "accommodation_excerpt": None if dismissed else excerpt,
        }

    def generate_email_draft(self, courses: list, extra_context: dict | None = None) -> str:
        """Real version: compiles selected courses' requirements/deadlines/
        accommodations into a templated subject + body.
        """
        extra_context = extra_context or {}
        professor = extra_context.get("professor_name", "").strip() or "[Professor Name]"
        return (
            f"Subject: Accommodation Request\n\n"
            f"Dear Professor {professor},\n\n"
            f"[Placeholder — personalized email generated by AI will appear "
            f"here once the Claude API is connected.]\n\n"
            f"Best regards,\n[Your Name]"
        )

    def get_policy_answer(self, question: str) -> str:
        """Real version: sends `question` to the Claude API and returns
        a generated answer.
        """
        return (
            f"**[Placeholder response]**\n\nYou asked: _\"{question}\"_\n\n"
            "This is where an AI-generated answer will appear once the "
            "Claude API is connected."
        )